# Site
name: "PaisaPro"
title: "PaisaPro"
description: "Best Personal Finance Guide In India"
logo: 'assets/images/logo_paisapro.png'
favicon: 'assets/images/logo_paisapro.png'
baseurl: "/paisapro"
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
rating: 4.5

# Authors
authors:
  shikha:
    name: Shikha
    display_name: Shikha
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: hello.moneyplan@gmail.com
    web: https://linkedin.com/in/shikha-bharti
    linkedin: https://linkedin.com/in/shikha-bharti
    description: "Personal Finance and Derivatives Trading enthusiast"
  nk:
    name: NK
    display_name: NK    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: hello.moneyplan@gmail.com
    web: https://paisapro.in
    linkedin: https://linkedin.com/in/shikha-bharti
    description: "All things money"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

#collections
collections:
  pages:
    output: true
    permalink: /:path/
  
  posts:
    output: true
    permalink: /:path/